### ISSUE TITLE
R1CBU feature roadmap

### ISSUE THREAD

**Issue by PCBenetton** [gdyuldin/x6100_gui#14]
The "original" feature roadmap from R1CBU is still being considered?
A couple of features on that list that would be nice to have are the WSPR Rx/tx and portrait mode.
Are there other features already mapped out for development?
Maybe it would be nice to have a list of features and status on the main page, akin to the R1CBU overview page. 
Thanks! And great work, as always!
73 DE PP2PB

**Comment by gdyuldin** [comment]
Well, right now I have no well defined and prioritized roadmap. 
I setup a GitHub discussions (https://github.com/gdyuldin/x6100_gui/discussions) and add few ideas. Let's use it to adding and track ideas about new features.
Regarding WSPR - seems, I need to find a suitable C library for decoding/encoding. 
From my point of view portrait mode looks like a huge task. I'm still not so experienced with LVGL GUI library - maybe I missed something, that will make this task simpler.

Also, there is a low priority tasks for creating a some kind of the user guide and redesign UI (at least color scheme).

73!
