### ISSUE TITLE
Output-Power issue v.0.24

### ISSUE THREAD

**Issue by HB9JOI** [gdyuldin/x6100_gui#2]
Hoi Georgyi ...
 
FW-Image v.0.24 / output-power issue (???)
...there seems to be again (known from earlier versions) the power issue in FT8 :  
(with built-in X6100 wattmeter !)
20m only 1 watt , 17m/15m also only 1... watt .
12m/10m 3 ... watt. 80m/60m/40m30m : 4 ... watts.
In CW always on all bands more than 10 ... (11) watts , ok.

73/76 Jens , HB9JOI

*****update-1
... just burned a second new image (v0.24.0) :
(with built-in X6100 wattmeter !)
Now FT8 output-power seems to be ok , nominal 4....5 watts .
**BUT : immediately if the RX-PREAMP. will switched to ON ... (or is ON)
then the FT8 output-power goes down to 1... watt !** (Like described before.)

*****update-2
NOW NEW FT8 measurement done (with calibrated dig.Power-Meter):
- 20m : max. 3,12 watt
- 15m : max. 2,45 watt
All other bands are ok , between 4,8 ... 5,25 watts
 
73/76 Jens / HB9JOI

**Comment by gdyuldin** [comment]
Hi Jens.
I just repeat my thoughts from groups.io:
This issue is likely due to hardware variations. I'm going to add automatic signal level adjustment for FT8 - hope it will help.
