### ISSUE TITLE
Doesnt allow long WIFI passwords

### ISSUE THREAD

**Issue by scm2000** [gdyuldin/x6100_gui#25]
Apparently my wifi password is longer than allowed to be typed
The max len allowed for WPA/WPA2 is 63, and the gui only allows you to enter 40

**Comment by scm2000** [comment]
thats 63 for alpha numeric and 64 for hexadecimal passwords. 
the problem line appears to be

v_textarea_set_max_length(text, 40);
in textarea_window.c

**Comment by gdyuldin** [comment]
Thanks for your report. I'll check.
As a temporal solution you can:
1. connect to radio with usb cable
2. launch `nmtui`
3. select `Activate a connection`
4. select your network and type a password.

GUI application uses the same library for wifi connection (`libnm`). After successful connection with `nmtui` connection parameters will be saved on the system and you will be able to use this saved connection within GUI application without need to provide a password.

**Comment by scm2000** [comment]
Thanks.  I'll need a bit more help though... 
I assume you mean connect my computer to the dev usb port, and use a terminal emulator...  which of the two com ports, and what baud?
If not that, what?
Thanks again.

**Comment by gdyuldin** [comment]
Yes. You can use PuTTY under windows.
Baud is 115200. Not sure about correct port number, but you can try both. After connecting - press enter. It should ask a password, if not - try another COM port. Login is root, password is 123.

**Comment by scm2000** [comment]
> Yes. You can use PuTTY under windows. Baud is 115200. Not sure about correct port number, but you can try both. After connecting - press enter. It should ask a password, if not - try another COM port. Login is root, password is 123.

That all worked, thanks!
