### ISSUE TITLE
adjusting bandwidth filters in CW only half applies to computer audio

### ISSUE THREAD

**Issue by jflinchbaugh** [gdyuldin/x6100_gui#26]
Version 0.26.0.

Changing the high or low filter in CW applies symmetrically on the radio, but not symmetrically on the computer audio.

Reproduction:
1. Open a monitor on the computer with an audio waterfall, like wsjtx, and switch the radio over to CW mode.
2. Observe the narrower width of the signal on the wsjtx waterfall. That's fine.
3. On the radio, move the Filter High (or Filter Low)
4. Notice that the _other filter_ setting on the radio has also moved symmetrically with the filter you moved.
5. BUT, observe that the waterfall on the computer only moved the one side you touched. The other side, while updated in the radio, was not applied to the audio to the computer (via the USB port).

Work-around: switch CW-R and back to CW, and it will have applied the filter to both sides of the audio output.

**Comment by gdyuldin** [comment]
Hi. Thanks for your report. I'll check.
