### ISSUE TITLE
Constant "transmit" spike on selected frequency showing on waterfall - CB, SSB.

### ISSUE THREAD

**Issue by marcbirkett** [gdyuldin/x6100_gui#46]
Hi,

I'm doing well on FT8 but whatever frequency I select I get a constant transmit spike showing on the waterfall as per the picture. Any way to get rid? I'm reasonably sure it isn't transmitting, however, it makes the waterfall difficult to use. Otherwise, enjoying it very much, good work!
![selected-frequency-spike](https://github.com/user-attachments/assets/dd2d87d3-0972-48d3-84b9-cbb8c6069cfe)

Ta

Marc

**Comment by gdyuldin** [comment]
Application uses I and Q signals from the BASE board to calculate spectrum and waterfall. Could you check it:
* without connected power (using internal battery)? Perhaps, it's a noise from power line.
* with turned off wifi module. It also might be a source of noise.
* with turned off display (short press on power button). Then, after turning on - check the difference between waterfall.
* using original firmware (Just turhn radio off, pull SD card and boot)

**Comment by marcbirkett** [comment]
hi, thanks for the reply.

1 - it is still present when on internal battery
2 - it is still present with the wifi turned off
3 - makes no difference
4 - it is present on original firmware, but much, much smaller as per attached.

![transmit-spike-original](https://github.com/user-attachments/assets/bfff4587-bbfa-468a-85eb-12efc72dc722)

Commonly the waterfall "freezes" too and I have to reboot the machine, i'm adjusting the settings to look at that too.

Thanks for your input.

Ta

Marc

**Comment by marcbirkett** [comment]
Error logs below, spike and waterfall freezes requiring restart.

[x6100_log_2024-11-27_13-52-36.txt](https://github.com/user-attachments/files/17935571/x6100_log_2024-11-27_13-52-36.txt)
[x6100_log_2024-11-27_13-54-56.txt](https://github.com/user-attachments/files/17935572/x6100_log_2024-11-27_13-54-56.txt)

**Comment by marcbirkett** [comment]
I can, testing now.

**Comment by marcbirkett** [comment]
hi, that has solved the waterfall locking up. Awesome! The spike on the selected frequency remains, but nothing in the log about it

**Comment by gdyuldin** [comment]
As far as I know - xiegu made some different HW versions. It might be a reason. You could try to flash a different version of the BASE firmware, but I'm not sure, that it will help.

**Comment by marcbirkett** [comment]
HW? I'm on the most recent firmware at the moment, will give it a try

**Comment by marcbirkett** [comment]
tried 4 different base units, all pretty unusable for SSB as per picture. never mind, made contacts on FT8. Will keep upgrading firmware as it becomes available. Thanks for your efforts, this can be closed.
![wf](https://github.com/user-attachments/assets/5d05149f-8922-4172-8470-2dac034b10d7)
