### ISSUE TITLE
Answering POTA CQ

### ISSUE THREAD

**Issue by w4rin** [gdyuldin/x6100_gui#7]
When using FT8 and answering a station calling CQ POTA, it uses POTA as the call sign. 

Awesome work!
Thanks,
W4RIN

**Comment by gdyuldin** [comment]
Hi. I know this issue. Try to fix in the next release.

**Comment by w4rin** [comment]
Sounds great and thank you for the awesome software!

**Comment by W8LID** [comment]
> Hi. I know this issue. Try to fix in the next release.

I fixed this with a simple solution by changing line 1393 of dialog_ft8.c to

`if (strlen(call_de) == 2 || strcmp(call_de, "POTA") == 0) {`

I tested it and it works but I think a more complete solution is needed, found this out when I was testing and came across a SOTA station :). I'm having trouble just building the application and have to do the whole buildroot, my linux skills are rusty, installed it on a machine just to try this out.

![2024-10-14 20-10-25](https://github.com/user-attachments/assets/e5d2d581-4184-4d39-aa6d-d67ef7e7bfbe)

**Comment by gdyuldin** [comment]
Thank you for your suggestion. 
I'm going to add a function to check CQ modifiers - such function will be also useful for #8.

**Comment by w4rin** [comment]
Awesome, thank you so much!

73,
W4RIN
