### ISSUE TITLE
Support of CQ modiffiers

### ISSUE THREAD

**Issue by gdyuldin** [gdyuldin/x6100_gui#8]
Add support of the CQ modifiers (POTA, WWFF, IOTA , BOTA, etc.) to FT8 application

**Comment by gdyuldin** [comment]
"CQ may be followed by a modifier with three decimal digits or one to four letters" (from https://wsjt.sourceforge.io/FT4_FT8_QEX.pdf)

**Comment by trbgithub** [comment]
+1 on this. Getting this in would make the X6100 the perfect all-in-one platform for POTA.

Seriously though, great work on this already man. Really outstanding. Been running FT8 with it all day and it rocks.

73

Ryan B / KQ4LLM
